language: ruby
rvm:
  - 2.1.0
before_script:
  - cp config/initializers/hosting.rb.example config/initializers/hosting.rb
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database knowledge_test;'
  - RAILS_ENV=test bundle exec rake db:migrate
script:
  - bundle exec rake spec
notifications:
  mails:
    - i2bskn@gmail.com
